### ISSUE TITLE
Is filex Thread safe? when to call fx_media_flush?

### ISSUE THREAD

**Issue by zhangshengping** [azure-rtos/filex#10]
I call fx_media_flush in a standalone threadx every 500ms, and call fx_file_write in other other thread. 
But I got HardFault.
what's wrong?

**Comment by TiejunMS** [comment]
If you are not running in standalone mode (FX_STANDALONE_ENABLE not defined), it is thread safe. Each FileX API is protection by FX_PROTECT. Could you check the definition of FX_PROTECT in your fx_port.h?

**Comment by Linjieqiang** [comment]
Hello @TiejunMS . Our code is like this.

```
static void thread_fs_entry(ULONG thread_input)
{
    (void)thread_input;

    fx_media_open_notify_set(&sd_disk, fs_media_opened_notify_cb);

    static uint8_t media_memory[512] __attribute__((section("DMA_RAM")));

    const UINT status = fx_media_open(&sd_disk, "SD_CARD", fx_stm32_sd_driver, 0, media_memory, sizeof(media_memory));
    if (status != FX_SUCCESS)
    {
        tx_thread_terminate(&thread_fatfs);
        return;
    }

/* Check the media and correct all errors. */
#if 0
    UCHAR sratch_memory[2048];
    ULONG detected_errors;
    fx_media_check(&sd_disk, sratch_memory, sizeof(sratch_memory),
                   FX_FAT_CHAIN_ERROR | FX_DIRECTORY_ERROR | FX_LOST_CLUSTER_ERROR, &detected_errors);
#endif

    ULONG64 available_bytes;
    fx_media_extended_space_available(&sd_disk, &available_bytes);
    log_i("tf card available bytes: %d MB\n", available_bytes / 1024 / 1024);

    while (1)
    {
        if (fx_media_flush(&sd_disk) != FX_SUCCESS)
        {
            tx_thread_terminate(&thread_fatfs);
        }

        tx_thread_sleep(500);
    }
}
```
But when we write synchronously, we will enter a hardware error.

**Comment by Linjieqiang** [comment]
By the way, the "FX_PROTECT" and "FX_UNPROTECT" is defined.

![image](https://user-images.githubusercontent.com/10217966/123358369-f449ef80-d59d-11eb-9fb6-00fa75cfacdb.png)

**Comment by TiejunMS** [comment]
It looks like the address of semaphore_ptr is invalid, could you double check? And what is the stack size of each thread? Try to use a large value (such as 4096) to validate if it is stack issue.

**Comment by Linjieqiang** [comment]
```
void fs_init(void)
{
    /** Initialize FileX. */
    fx_system_initialize();

    /** 创建线程 */
    static uint8_t _thread_stack[1500];
    tx_thread_create(&thread_fatfs,
                     "file system idle",
                     thread_fs_entry,
                     0,
                     &_thread_stack[0],
                     sizeof(_thread_stack),
                     TX_THREAD_PRIORITY_FILE_SYSTEM,
                     TX_THREAD_PRIORITY_FILE_SYSTEM,
                     TX_NO_TIME_SLICE,
                     TX_AUTO_START);
}
```

I will improve the thread_fatfs stack size to 4096 bytes to try again.

**Comment by Linjieqiang** [comment]
![image](https://user-images.githubusercontent.com/10217966/123361565-dd0d0100-d5a1-11eb-9354-0ded5e317bb2.png)

But there seems to be a new problem. I use the STM32F405RGT6 MCU.

**Comment by Linjieqiang** [comment]
![image](https://user-images.githubusercontent.com/10217966/123362079-b69b9580-d5a2-11eb-9675-2850ffd03aef.png)

**Comment by TiejunMS** [comment]
For ST HAL issue, could you check with ST support?

When there is hardfault at line 279 of fx_utility_logical_sector_read, what is the value of cache entry? I suspect that the stack is corrupted somewhere else but it hits hardfault here.

**Comment by Linjieqiang** [comment]
The problem has been resolved. Thanks for your support. @TiejunMS This is not a problem with the Filex file system
