### ISSUE TITLE
Const keyword is missing for data parameter

### ISSUE THREAD

**Issue by MaJerle** [azure-rtos/filex#13]
https://github.com/azure-rtos/filex/blob/3f4d2b5e35fc6728b534f84a7e86735527dd5bb5/common/src/fx_file_write.c#L100

**Comment by weycen** [comment]
FileX will ensure that the incoming BUFFER will not be modified, so I think it is not necessary to use const keyword here.

**Comment by MaJerle** [comment]
Unfortunately this is not enough guaranty for aurhorities. Passing const pointer will reault in at least warning, if not even error in some compilers.

Adding const has added value at robustness level and is not introducing backward compatibility break.

**Comment by weycen** [comment]
You are right. Const keyword is added in many other codes for data parameter, but I read FileX such as fx_file_write(), fx_media_write(), these functions are not added, all the source code is only some constant arrays use const, such as `static const USHORT diff_table_range_low[]`.

**Comment by bhnaphade** [comment]
@MaJerle  Thank you for the feedback. We will review this and add a fix soon.
