### ISSUE TITLE
Filex drivers for Microchip SAME54 Xplained Pro?

### ISSUE THREAD

**Issue by imogano** [azure-rtos/filex#15]
Hi, I hope this finds you well. 

I need assistance with obtaining filex drivers for the above mentioned board, my goal is to run the demo application example that is included in the api.

User guides, examples and/or video(s) are welcomed.

Regards

**Comment by goldscott** [comment]
There is a ram disk example in the [sample](https://github.com/azure-rtos/samples) we provide. For interfacing with real storage hardware (e.g. a flash chip), you'll need to write your own driver.
