### ISSUE TITLE
Parse SD card 

### ISSUE THREAD

**Issue by BlueShark7** [azure-rtos/filex#16]
Hi, 
Which API FX to use to parse SD media files (name and extension) after opening media.

**Comment by bhnaphade** [comment]
Hello @BlueShark7 
There is no direct api for parsing the files.
You can use the fx_directory_first_entry_find() to find the first entry and fx_directory_next_entry_find() to find the subsequent entries.
Here is the list of FileX services : [Azure RTOS FileX documentation](https://docs.microsoft.com/en-us/azure/rtos/filex/appendix-a)

**Comment by ayed-m** [comment]
@bhnaphade  Thanks :)
