### ISSUE TITLE
The spi flash initialization parameter is missing

### ISSUE THREAD

**Issue by cliffcloudlong** [azure-rtos/filex#18]
I was initializing the spi flash using fx_media_format and then calling fx_media_open (how was it also done on the routine).The result is that fx_media_open returns FX_BUFFER_ERROR (here if (media_ptr- & gt; fx_media_sector_cache_size == 0)), After tracing, I found that the parameters are gone, Follow the fx_media_open.c line 298 (media_ptr- & gt; fx_media_driver_entry) (media_ptr); The parameters will change here to 0xFF, Occasionally no changes.Now I am blocking it and can initialize spi flash every time.

fx_media_open.c line 298 follows:
`#if 0
    /* Invoke the driver to read the boot sector.  */
    (media_ptr -> fx_media_driver_entry) (media_ptr);// mark

    /* Determine if the boot sector was read correctly. */
    if (media_ptr -> fx_media_driver_status != FX_SUCCESS)
    {

        /* Build the "uninitialize" I/O driver request.  */
        media_ptr -> fx_media_driver_request =      FX_DRIVER_UNINIT;
        media_ptr -> fx_media_driver_status =       FX_IO_ERROR;

        /* If trace is enabled, insert this event into the trace buffer.  */
        FX_TRACE_IN_LINE_INSERT(FX_TRACE_INTERNAL_IO_DRIVER_UNINIT, media_ptr, 0, 0, 0, FX_TRACE_INTERNAL_EVENTS, 0, 0)

        /* Call the specified I/O driver with the uninitialize request.  */
        (media_ptr -> fx_media_driver_entry) (media_ptr);

        /* Return the boot sector error status.  */
        return(FX_BOOT_ERROR);
    }
#endif`

**Comment by bhnaphade** [comment]
@cliffcloudlong  could you please share the options details used for  fx_media_format() ?

**Comment by cliffcloudlong** [comment]
`status =  fx_media_format(&spi_nor_disk,
					fx_spi_flash_driver,		  // Driver entry
					(VOID*)W25Q128JYSQ_ID,		  // Driver info
					(UCHAR*)media_memory,				  // Media buffer pointer
					sizeof(media_memory),		  // Media buffer size
					"MY_RAM_DISK",				  // Volume Name
					1,							  // Number of FATs
					32, 						  // Directory Entries
					0,							  // Hidden sectors
					0x8000,//0x1000000/512, 			   // Total sectors
					512,						  // Sector size
					8,							  // Sectors per cluster
					1,							  // Heads
					1); 						  // Sectors per track`

**Comment by cliffcloudlong** [comment]
Is the driver problem that I have solved.
