### ISSUE TITLE
Release tag behind ThreadX and different prefix?

### ISSUE THREAD

**Issue by josesimoes** [azure-rtos/filex#19]
Hi,

Is there a reason for the FileX release tag being behind the other ThreadX components? 
And also the prefix is `r` when all the others are `v`...

**Comment by goldscott** [comment]
If there are no changes, there's no reason to bump it to the same version. I am also not sure why it is 'r' (for 'release' probably) rather than 'v' for 'version.' Thanks for pointing out this inconsistency. We'll make an effort to change it.
