### ISSUE TITLE
Why you implement your own memset?

### ISSUE THREAD

**Issue by smithBraun** [azure-rtos/filex#21]
https://github.com/azure-rtos/filex/blob/3b203634dce8fc51e77ac67ec28d91d693c2c570/common/src/fx_utility_memory_set.c#L82-L92

Standard libraries/compilers may optimize memcpy much more than what done here

**Comment by TiejunMS** [comment]
Hi @smithBraun , it was from old design. Most of modem compilers are able to optimize `_fx_utility_memory_set` to `memset`. See example [here](https://godbolt.org/z/8Y8W1ax1M).
