### ISSUE TITLE
如何创建中文文件名？

### ISSUE THREAD

**Issue by FlyyingPiggy2020** [azure-rtos/filex#27]
我在SD卡中构建了文件系统 ，并使用fx_directory_create创建中文的文件夹。
然后在PC上查看它，发现它是乱码。

**Comment by BeeeeeeLazy** [comment]
![image](https://user-images.githubusercontent.com/62139687/180599311-e33d16ab-248f-41b2-acc9-efa331bd50c7.png)

**Comment by xiuwencai** [comment]
Hi @BeeeeeeLazy , fx_directory_create does not support Chinese characters, use fx_unicode_directory_create to create directory with Chinese characters.
